version: "3.9"
services:
  app:
    image: mediawiki-mcp:v1.0
    env_file:
      - .mcp.env
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.wikichat.rule=Host(`chat.yuri.rs`)
      - traefik.http.routers.wikichat.entrypoints=websecure
      - traefik.http.routers.wikichat.service=wikichat
      - traefik.http.services.wikichat.loadbalancer.server.port=18080